# generated by datamodel-codegen:
#   filename:  audit.schema.json
#   timestamp: 2026-04-25T18:36:48+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Agent(Enum):
    claude = 'claude'
    codex = 'codex'
    gemini = 'gemini'
    grok = 'grok'
    oss_qwen = 'oss-qwen'
    oss_gemma4 = 'oss-gemma4'
    oss_nemotron = 'oss-nemotron'
    oss_llama_guard = 'oss-llama-guard'
    oss_nomic_embed = 'oss-nomic-embed'


class AgentRole(Enum):
    implementer = 'implementer'
    auditor = 'auditor'
    verifier = 'verifier'
    security = 'security'
    currency = 'currency'
    redactor = 'redactor'
    multimodal = 'multimodal'
    embeddings = 'embeddings'


class AuditStatus(Enum):
    signed_off = 'signed_off'
    needs_changes = 'needs_changes'
    blocked = 'blocked'
    inconclusive = 'inconclusive'
    redaction_required = 'redaction_required'


class QuotaConsumed(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokens_in: int | None = None
    tokens_out: int | None = None
    percent_weekly: float | None = None
    api_calls: int | None = None


class Severity(Enum):
    critical = 'critical'
    high = 'high'
    medium = 'medium'
    low = 'low'
    advisory = 'advisory'


class Category(Enum):
    correctness = 'correctness'
    security = 'security'
    performance = 'performance'
    architecture = 'architecture'
    style = 'style'
    currency = 'currency'
    redaction = 'redaction'
    test_coverage = 'test_coverage'
    documentation = 'documentation'


class Finding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    severity: Severity
    category: Category
    file: str | None = None
    line: conint(ge=1) | None = None
    feature_id: constr(pattern=r'^F\d{3}$') | None = None
    issue: constr(min_length=10)
    evidence: str | None = Field(None, description='What the agent actually observed')
    recommendation: str | None = None


class Audit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    audit_id: str = Field(
        ..., description='task_id + agent + iteration (e.g., 2026-04-19-001...#codex#2)'
    )
    agent: Agent
    agent_role: AgentRole
    model_version: str | None = None
    iteration: conint(ge=0)
    started_at: AwareDatetime
    completed_at: AwareDatetime
    audit_status: AuditStatus
    findings: list[Finding] | None = None
    validation_performed: list[str] | None = None
    quota_consumed: QuotaConsumed | None = None
    summary: str | None = Field(
        None, description='One-paragraph human-readable summary'
    )
