# generated by datamodel-codegen:
#   filename:  environments.schema.json
#   timestamp: 2026-04-26T01:17:08+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class EnvBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    firebase_project: str | None = Field(
        None,
        description='Firebase project ID (e.g., your-app-dev). Identical to gcp_project when the project is Firebase-managed.',
    )
    gcp_project: str | None = Field(
        None,
        description='GCP project ID. Often equal to firebase_project for Firebase-on-GCP projects.',
    )
    xcode_scheme: str | None = Field(
        None,
        description='Xcode scheme name for iOS deploys (e.g., GlamSwift-Dev). Omit for non-iOS repos.',
    )
    bundle_id: str | None = Field(
        None, description='iOS bundle identifier for this tier. Omit for non-iOS repos.'
    )
    hosting_target: list[str] | None = Field(
        None,
        description="firebase.json hosting target names (e.g., ['admin', 'web']). Omit if the repo uses a single anonymous hosting block or has no Firebase Hosting.",
    )
    allowed_deploy_commands: list[str] | None = Field(
        None,
        description='Operator policy: explicit deploy command patterns allowed for this tier. Reserved for F023 EC11/EC12 — may be omitted in EC1+EC8 starter files and added later.',
    )
    requires_gates: list[str] | None = Field(
        None,
        description='Operator policy: human_gates names required before any dispatch to this tier. Reserved for F023 EC11/EC12 — may be omitted in EC1+EC8 starter files and added later.',
    )


class Environments(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    repo: str = Field(
        ...,
        description='Repo name. Advisory label; loader discovers the file via path-based walk-up from a plan dir.',
    )
    dev: EnvBlock | None = None
    staging: EnvBlock | None = None
    prod: EnvBlock | None = None
