# generated by datamodel-codegen:
#   filename:  features.schema.json
#   timestamp: 2026-04-25T18:36:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint, constr


class Category(Enum):
    functional = 'functional'
    infra = 'infra'
    schema = 'schema'
    test = 'test'
    doc = 'doc'
    security = 'security'
    observability = 'observability'
    tooling = 'tooling'


class TierOverride(Enum):
    trivial = 'trivial'
    local = 'local'
    cross_cutting = 'cross-cutting'
    architectural = 'architectural'
    p0 = 'p0'


class Type(Enum):
    screenshot = 'screenshot'
    log = 'log'
    test_output = 'test_output'
    diff = 'diff'
    audit_json = 'audit_json'
    commit = 'commit'
    url = 'url'
    file = 'file'


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    uri: str = Field(
        ..., description='Relative path, git SHA, or Firebase Storage signed URL'
    )
    hash: str | None = Field(None, description='SHA-256 of content for integrity')
    captured_at: AwareDatetime | None = None
    captured_by: str | None = Field(
        None, description='Agent or tool that captured the evidence'
    )
    note: str | None = None


class Feature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^F\d{3}$') = Field(..., description='F001, F002, ...')
    category: Category
    description: constr(min_length=10)
    steps: list[str] | None = Field(
        None, description='Verification steps the verifier must perform end-to-end'
    )
    acceptance: str = Field(
        ..., description='Machine-checkable condition — the exact test for passes=true'
    )
    passes: bool
    verified_by: list[str] | None = None
    verified_at: AwareDatetime | None = None
    evidence_refs: list[EvidenceRef] | None = None
    depends_on: list[constr(pattern=r'^F\d{3}$')] | None = None
    phase: conint(ge=0, le=9) | None = None
    tier_override: TierOverride | None = Field(
        None, description='Force different audit tier for this feature only'
    )


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str = Field(..., description='Parent plan ID')
    schema_version: Literal['1.0']
    features: list[Feature] = Field(..., min_length=1)
