# generated by datamodel-codegen:
#   filename:  features.schema.json
#   timestamp: 2026-04-25T18:36:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    conint,
    constr,
    model_validator,
)


class Category(Enum):
    functional = 'functional'
    infra = 'infra'
    schema = 'schema'
    test = 'test'
    doc = 'doc'
    security = 'security'
    observability = 'observability'
    tooling = 'tooling'


class TierOverride(Enum):
    trivial = 'trivial'
    local = 'local'
    cross_cutting = 'cross-cutting'
    architectural = 'architectural'
    p0 = 'p0'


class Type(Enum):
    screenshot = 'screenshot'
    log = 'log'
    test_output = 'test_output'
    diff = 'diff'
    audit_json = 'audit_json'
    commit = 'commit'
    url = 'url'
    file = 'file'


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    uri: str = Field(
        ..., description='Relative path, git SHA, or Firebase Storage signed URL'
    )
    hash: str | None = Field(None, description='SHA-256 of content for integrity')
    captured_at: AwareDatetime | None = None
    captured_by: str | None = Field(
        None, description='Agent or tool that captured the evidence'
    )
    note: str | None = None
    # --- Experience Readiness typing fields (plan 2026-06-15-001 F001) --------
    # All optional + backward-compatible: an EvidenceRef carrying none of these
    # is a legacy/untyped ref (F002 treats human-family untyped evidence as
    # not_yet_typed). Validated against the closed experience_readiness enums.
    evidence_class: str | None = Field(
        None, description='Closed evidence_class enum (experience_readiness)'
    )
    data_provenance: str | None = Field(
        None, description='seeded | real | degraded'
    )
    data_source: str | None = Field(None, description='Stable key the evidence proves')
    availability: str | None = Field(None, description='available | unavailable')
    consumer_family: str | None = Field(None, description='human | agent')
    degraded_mode: str | None = Field(
        None, description='Selected degraded mode (required when data_provenance=degraded)'
    )
    surface_class: str | None = Field(
        None, description='Closed surface_class enum naming the surface this evidence attests'
    )

    @model_validator(mode='after')
    def _validate_experience_readiness_typing(self) -> 'EvidenceRef':
        # Lazy + path-robust import: the models dir may be on sys.path directly
        # (top-level import) or via the `models` package (harness inserts v1.0).
        try:
            from experience_readiness import validate_evidence_typing
        except ImportError:  # pragma: no cover - import-path fallback
            from models.experience_readiness import validate_evidence_typing
        validate_evidence_typing(
            surface_class=self.surface_class,
            consumer_family=self.consumer_family,
            availability=self.availability,
            data_source=self.data_source,
            data_provenance=self.data_provenance,
            degraded_mode=self.degraded_mode,
            note=self.note,
            evidence_class=self.evidence_class,
        )
        return self


class Feature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^F\d{3}$') = Field(..., description='F001, F002, ...')
    category: Category
    description: constr(min_length=10)
    steps: list[str] | None = Field(
        None, description='Verification steps the verifier must perform end-to-end'
    )
    acceptance: str = Field(
        ..., description='Machine-checkable condition — the exact test for passes=true'
    )
    passes: bool
    verified_by: list[str] | None = None
    verified_at: AwareDatetime | None = None
    evidence_refs: list[EvidenceRef] | None = None
    depends_on: list[constr(pattern=r'^F\d{3}$')] | None = None
    introduces: list[str] | None = Field(
        None,
        description=(
            'Symbols (code identifiers) this feature DEFINES. plan-review honors '
            'these as locally-defined for this feature and any later feature in '
            'plan order, so a greenfield/contract plan that introduces new '
            'vocabulary does not self-deadlock the missing_prereq lint.'
        ),
    )
    phase: conint(ge=0, le=9) | None = None
    tier_override: TierOverride | None = Field(
        None, description='Force different audit tier for this feature only'
    )


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str = Field(..., description='Parent plan ID')
    schema_version: Literal['1.0']
    features: list[Feature] = Field(..., min_length=1)
