# generated by datamodel-codegen:
#   filename:  features.schema.json
#   timestamp: 2026-04-25T18:36:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    conint,
    constr,
    model_validator,
)


class Category(Enum):
    functional = 'functional'
    infra = 'infra'
    schema = 'schema'
    test = 'test'
    doc = 'doc'
    security = 'security'
    observability = 'observability'
    tooling = 'tooling'


class TierOverride(Enum):
    trivial = 'trivial'
    local = 'local'
    cross_cutting = 'cross-cutting'
    architectural = 'architectural'
    p0 = 'p0'


class Type(Enum):
    screenshot = 'screenshot'
    log = 'log'
    test_output = 'test_output'
    diff = 'diff'
    audit_json = 'audit_json'
    commit = 'commit'
    url = 'url'
    file = 'file'


class Audience(Enum):
    end_user = 'end_user'
    operator = 'operator'
    agent = 'agent'
    none = 'none'


class ImpactSurface(Enum):
    """Mirrors the plan-level `surfaces` enum in plan.schema.json.

    Kept in lockstep with features.schema.json's `$defs/user_impact` — the two
    JSON enums are asserted identical by scripts/test_user_impact_contract.py.
    """

    web = 'web'
    ios = 'ios'
    android = 'android'
    backend = 'backend'
    infra = 'infra'
    security = 'security'
    data = 'data'
    ux = 'ux'
    ml = 'ml'
    docs = 'docs'
    external_api_wrap = 'external-api-wrap'


class ProofMethod(Enum):
    """How a feature's cheap proof is taken.

    Identical to `objective_contract.schema.json`'s `delivers[].proof.method`
    — the two enums are kept in lockstep so a slice means the same thing
    whether it was declared in the contract or carried by the feature.
    """

    walk = 'walk'
    request = 'request'
    named_test = 'named_test'
    probe = 'probe'


class ProofSurface(Enum):
    """Where a proof is taken. Mirrors the plan-level `surfaces` enum."""

    web = 'web'
    ios = 'ios'
    android = 'android'
    backend = 'backend'
    infra = 'infra'
    security = 'security'
    data = 'data'
    ux = 'ux'
    ml = 'ml'
    docs = 'docs'
    external_api_wrap = 'external-api-wrap'


class Proof(BaseModel):
    """The cheap first-principle proof a feature carries on its own.

    A feature carrying one is scored as a slice in its own right (plan
    2026-08-13-001 F002), so a plan whose features each carry a proof states
    an outcome without any `delivers[]`. Same shape as the contract-level
    `delivers[].proof`.
    """

    model_config = ConfigDict(extra='forbid')
    metric: str = Field(..., min_length=10)
    method: ProofMethod
    surface: ProofSurface | None = None

    @model_validator(mode='before')
    @classmethod
    def _reject_explicit_nulls(cls, data: object) -> object:
        """Mirror the schema, which types these fields with no `null` member."""
        if isinstance(data, dict):
            for key in ('metric', 'method', 'surface'):
                if key in data and data[key] is None:
                    raise ValueError(
                        f'{key} must be omitted rather than set to null'
                    )
        return data


class UserImpact(BaseModel):
    """Declared user impact — who feels this feature and how.

    Hand-maintained mirror of the `if/then/else` in features.schema.json.
    datamodel-codegen drops JSON Schema conditionals, so the conditional
    semantics of D003 live in `_check_audience_conditional` below rather than
    in generated field constraints.

    The optional fields below are absent-or-typed, never explicitly null: the
    JSON Schema types them `string`/`array` with no `"null"` member, so a
    literal `null` is a schema violation. `_reject_explicit_nulls` keeps the
    Pydantic side from silently coercing that null to a default and returning
    the opposite verdict.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    audience: Audience = Field(
        ...,
        description=(
            "Who experiences the change. 'none' means genuinely internal work "
            'with no external consequence, and is a complete declaration on '
            'its own.'
        ),
    )
    summary: str | None = Field(
        None,
        description=(
            'One plain-language line naming what the audience experiences '
            "differently. Required (>=10 chars) unless audience is 'none'."
        ),
    )
    surfaces: list[ImpactSurface] | None = Field(
        None,
        description=(
            'Where the impact lands. Required (non-empty) unless audience is '
            "'none'."
        ),
    )
    description_hash: constr(pattern=r'^[a-f0-9]{64}$') | None = Field(
        None,
        description=(
            'SHA-256 hex digest of the UTF-8 encoded feature `description` '
            'this declaration was written against. Staleness anchor per D005: '
            'a mismatch marks the brief possibly-stale rather than presenting '
            'an old claim as current. Required whenever the declaration '
            "carries a claim (audience other than 'none'). Optional under "
            "audience 'none', which asserts no external consequence and so "
            'has no claim that can go stale.'
        ),
    )

    @model_validator(mode='before')
    @classmethod
    def _reject_explicit_nulls(cls, data: object) -> object:
        """Mirror the schema, which types these fields with no `null` member.

        Pydantic would otherwise read an explicit `null` as "use the default"
        and accept a document the JSON Schema rejects — the two validators must
        return the same verdict, which is the whole point of the block.
        """
        if isinstance(data, dict):
            for key in ('summary', 'surfaces', 'description_hash'):
                if key in data and data[key] is None:
                    raise ValueError(
                        f'{key} must be omitted rather than set to null'
                    )
        return data

    @model_validator(mode='after')
    def _check_audience_conditional(self) -> UserImpact:
        """D003 — 'none' is the whole declaration; anything else owes detail."""
        if self.audience is Audience.none:
            if self.summary:
                raise ValueError(
                    "audience 'none' is a complete declaration on its own — "
                    'summary must be absent or empty'
                )
            if self.surfaces:
                raise ValueError(
                    "audience 'none' is a complete declaration on its own — "
                    'surfaces must be absent or empty'
                )
        else:
            if self.summary is None or len(self.summary) < 10:
                raise ValueError(
                    f"audience '{self.audience.value}' requires a summary of "
                    'at least 10 characters'
                )
            if not self.surfaces:
                raise ValueError(
                    f"audience '{self.audience.value}' requires a non-empty "
                    'surfaces array'
                )
            if not self.description_hash:
                raise ValueError(
                    f"audience '{self.audience.value}' requires a "
                    'description_hash — D005 binds the claim to the '
                    'description it was written against, and F003 has no '
                    "'digest unknown' state to fall back to"
                )

        if self.surfaces is not None and len(set(self.surfaces)) != len(self.surfaces):
            raise ValueError('surfaces must not contain duplicates')

        return self


class EvidenceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    uri: str = Field(
        ..., description='Relative path, git SHA, or Firebase Storage signed URL'
    )
    hash: str | None = Field(None, description='SHA-256 of content for integrity')
    captured_at: AwareDatetime | None = None
    captured_by: str | None = Field(
        None, description='Agent or tool that captured the evidence'
    )
    note: str | None = None
    # --- Experience Readiness typing fields (plan 2026-06-15-001 F001) --------
    # All optional + backward-compatible: an EvidenceRef carrying none of these
    # is a legacy/untyped ref (F002 treats human-family untyped evidence as
    # not_yet_typed). Validated against the closed experience_readiness enums.
    evidence_class: str | None = Field(
        None, description='Closed evidence_class enum (experience_readiness)'
    )
    data_provenance: str | None = Field(
        None, description='seeded | real | degraded'
    )
    data_source: str | None = Field(None, description='Stable key the evidence proves')
    availability: str | None = Field(None, description='available | unavailable')
    consumer_family: str | None = Field(None, description='human | agent')
    degraded_mode: str | None = Field(
        None, description='Selected degraded mode (required when data_provenance=degraded)'
    )
    surface_class: str | None = Field(
        None, description='Closed surface_class enum naming the surface this evidence attests'
    )

    @model_validator(mode='after')
    def _validate_experience_readiness_typing(self) -> 'EvidenceRef':
        # Lazy + path-robust import: the models dir may be on sys.path directly
        # (top-level import) or via the `models` package (harness inserts v1.0).
        try:
            from experience_readiness import validate_evidence_typing
        except ImportError:  # pragma: no cover - import-path fallback
            from models.experience_readiness import validate_evidence_typing
        validate_evidence_typing(
            surface_class=self.surface_class,
            consumer_family=self.consumer_family,
            availability=self.availability,
            data_source=self.data_source,
            data_provenance=self.data_provenance,
            degraded_mode=self.degraded_mode,
            note=self.note,
            evidence_class=self.evidence_class,
        )
        return self


class Feature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^F\d{3}$') = Field(..., description='F001, F002, ...')
    category: Category
    description: constr(min_length=10)
    steps: list[str] | None = Field(
        None, description='Verification steps the verifier must perform end-to-end'
    )
    acceptance: str = Field(
        ..., description='Machine-checkable condition — the exact test for passes=true'
    )
    passes: bool
    verified_by: list[str] | None = None
    verified_at: AwareDatetime | None = None
    evidence_refs: list[EvidenceRef] | None = None
    depends_on: list[constr(pattern=r'^F\d{3}$')] | None = None
    introduces: list[str] | None = Field(
        None,
        description=(
            'Symbols (code identifiers) this feature DEFINES. plan-review honors '
            'these as locally-defined for this feature and any later feature in '
            'plan order, so a greenfield/contract plan that introduces new '
            'vocabulary does not self-deadlock the missing_prereq lint.'
        ),
    )
    phase: conint(ge=0, le=9) | None = None
    tier_override: TierOverride | None = Field(
        None, description='Force different audit tier for this feature only'
    )
    user_impact: UserImpact | None = Field(
        None,
        description=(
            'Optional declared user impact — who feels this feature and how. '
            'Consumed by the decision brief rendered at human approval gates. '
            'Optional by design (D003): a feature that declares nothing '
            "renders 'user impact not declared' rather than a synthesized "
            'claim.'
        ),
    )
    proof: Proof | None = Field(
        None,
        description=(
            'Optional cheap first-principle proof this feature carries on its '
            'own. A feature that carries one is scored as a slice in its own '
            'right by the lock/close scorer, so a plan whose features each '
            'carry a proof needs no delivers[] to state an outcome. Absence '
            'means the feature is not a slice, not that it is invalid.'
        ),
    )

    @model_validator(mode='before')
    @classmethod
    def _reject_explicit_null_user_impact(cls, data: object) -> object:
        """`user_impact` is absent or an object — the schema gives it no null.

        Scoped to `user_impact` because that is what this contract owns; the
        legacy optional fields above predate it and are left as they were.
        """
        if isinstance(data, dict) and data.get('user_impact', ...) is None:
            raise ValueError(
                'user_impact must be omitted rather than set to null'
            )
        return data

    @model_validator(mode='after')
    def _passes_true_requires_evidence(self) -> 'Feature':
        """A feature claiming `passes: true` must carry what backs the claim.

        `features.schema.json` has always required this — `verified_by`,
        `verified_at` and `evidence_refs`, the first and last non-empty — under
        an `if passes == true` conditional. This model did not, so the two
        validator arms disagreed: `validate.py` runs THIS arm and reported a
        clean plan while `jsonschema` on the same bytes reported three errors.

        The gap was not theoretical. An implementer flipped a feature to
        `passes: true` with all three fields absent and the plan validated
        clean (recorded as D008 on plan 2026-08-13-001). A flip is a claim that
        the acceptance was met; a claim with nothing behind it is precisely the
        failure this contract exists to prevent, and the validator was the one
        place guaranteed to be run.

        Scoped deliberately to `passes == true` — an open feature owes nothing.
        """
        if not self.passes:
            return self

        missing: list[str] = []
        if not self.verified_by:
            missing.append('verified_by')
        if self.verified_at is None:
            missing.append('verified_at')
        if not self.evidence_refs:
            missing.append('evidence_refs')

        if missing:
            raise ValueError(
                f'feature {self.id} claims passes=true but is missing '
                f'{", ".join(missing)} — a flip to true must name who verified '
                'it, when, and at least one evidence_ref. An empty list is not '
                'evidence.'
            )
        return self


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str = Field(..., description='Parent plan ID')
    schema_version: Literal['1.0']
    features: list[Feature] = Field(..., min_length=1)
