# generated by datamodel-codegen:
#   filename:  plan.schema.json
#   timestamp: 2026-05-11T20:22:53+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Type(Enum):
    feat = "feat"
    fix = "fix"
    refactor = "refactor"
    migration = "migration"
    infra = "infra"


class Tier(Enum):
    trivial = "trivial"
    local = "local"
    cross_cutting = "cross-cutting"
    architectural = "architectural"
    p0 = "p0"


class Status(Enum):
    draft = "draft"
    active = "active"
    ready_for_audit = "ready_for_audit"
    in_audit = "in_audit"
    completed = "completed"
    abandoned = "abandoned"
    blocked = "blocked"


class AgentsRequiredEnum(Enum):
    claude = "claude"
    codex = "codex"
    gemini = "gemini"
    grok = "grok"
    oss_qwen = "oss-qwen"
    oss_gemma4 = "oss-gemma4"
    oss_nemotron = "oss-nemotron"
    oss_llama_guard = "oss-llama-guard"
    oss_nomic_embed = "oss-nomic-embed"


class HumanGate(Enum):
    pre_impl = "pre_impl"
    pre_merge = "pre_merge"
    on_escalation = "on_escalation"
    tier_promotion = "tier_promotion"
    cost_trigger = "cost_trigger"


class QuotaCaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claude: confloat(ge=0.0, le=100.0) | None = None
    codex: confloat(ge=0.0, le=100.0) | None = None
    gemini: confloat(ge=0.0, le=100.0) | None = None
    grok_calls: conint(ge=0) | None = None


class LoopCaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_iterations: conint(ge=0) | None = None
    no_progress_threshold: conint(ge=1) | None = None
    wall_clock_hours: confloat(ge=0.0) | None = None
    hard_stop: bool | None = Field(
        None,
        description="true = terminate at cap; false (default) = pause for human approval via INBOX.md, reset counters on approval.",
    )


class PrivacyTier(Enum):
    public = "public"
    internal = "internal"
    secret = "secret"


class GoalType(Enum):
    mechanical = "mechanical"
    infra = "infra"
    refactor = "refactor"
    parity = "parity"
    new_feature = "new_feature"
    migration = "migration"
    incident = "incident"


class Surface(Enum):
    web = "web"
    ios = "ios"
    android = "android"
    backend = "backend"
    infra = "infra"
    security = "security"
    data = "data"
    ux = "ux"
    ml = "ml"
    docs = "docs"
    external_api_wrap = "external-api-wrap"


class Status1(Enum):
    open = "open"
    resolved = "resolved"
    deferred = "deferred"


class OpenDecision(BaseModel):
    id: str
    question: str
    status: Status1
    resolution: str | None = None


class Links(BaseModel):
    features: str | None = None
    decisions: str | None = None
    audits_dir: str | None = None
    evidence_dir: str | None = None
    objective_contract: str | None = Field(
        None,
        description="Path reference (relative to plan dir) to an ObjectiveContract JSON file. Required when goal_type ∈ {parity, new_feature, migration, incident}; the plan-level validator enforces presence + file-exists + ObjectiveContract validation.",
    )


class Backend(Enum):
    firebase_storage = "firebase-storage"
    r2 = "r2"
    local = "local"


class Storage(BaseModel):
    backend: Backend | None = None
    bucket: str | None = None
    prefix: str | None = None


# ──────────────────────────────  v1.9.0 nested-orchestration mirror  ──────────────────────────────
#
# Static mirror of the v1.9.0 plan.schema.json additive blocks (orchestration,
# child_charter, commit_policy). These sub-models match the JSON schema's
# enum + property contract literal-for-literal so `jsonschema.validate` and
# `Plan.model_validate` accept the same plan.md frontmatter shapes. The
# runtime nested-orchestration models in
# `scripts/dontpanic_orchestrate/nested_orchestration.py` may narrow further
# (e.g. tighter `requires` enum, cross-field invariants); this mirror is the
# outer perimeter the schema declares.


class SpawnReason(Enum):
    operator_manual = "operator_manual"
    auto = "auto"
    test = "test"


class Orchestration(BaseModel):
    """Child-plan nested-orchestration block (v1.9.0)."""

    parent_plan_id: str = Field(..., description="Plan ID of the parent plan.")
    spawn_reason: SpawnReason = Field(
        ...,
        description=(
            "'operator_manual' = operator-authored; 'auto' = automated spawn; "
            "'test' = synthetic fixture plan."
        ),
    )
    depth_limit: conint(ge=1) | None = Field(
        None,
        description=(
            "Per-plan depth cap (>=1). Frontmatter cannot raise the platform "
            "default; operator lifts at dispatch via --allow-depth."
        ),
    )


class ChildCharterKind(Enum):
    implementation = "implementation"
    investigation = "investigation"
    migration = "migration"


class ChildCharter(BaseModel):
    """Child-plan charter (v1.9.0)."""

    kind: ChildCharterKind = Field(
        ...,
        description=(
            "'implementation' ships code; 'investigation' produces evidence "
            "without shipping; 'migration' is a bounded schema/data migration."
        ),
    )
    parent_objective: constr(min_length=1, max_length=500) = Field(
        ..., description="What the parent needed when it spawned this child."
    )
    parent_acceptance_item: constr(min_length=1) = Field(
        ..., description="The parent acceptance clause this child unblocks."
    )
    allowed_paths: list[str] = Field(
        ...,
        min_length=1,
        description=(
            "fnmatch-style globs. Under commit_policy.mode='child_commit', "
            "the runtime requires every modified file to match at least one."
        ),
    )
    forbidden_decisions: list[str] = Field(
        default_factory=list,
        description="Free-form decisions the child must not take (informational).",
    )
    return_condition_summary: constr(min_length=1) = Field(
        ..., description="Observable signal text rendered into the close-out memo."
    )
    may_edit_product_code: bool = Field(
        ...,
        description=(
            "Whether the child may modify product code. NO default — operator "
            "must declare intent explicitly. Cross-field invariant with "
            "commit_policy.mode enforced by the runtime."
        ),
    )


class CommitPolicyMode(Enum):
    child_commit = "child_commit"
    parent_commit = "parent_commit"
    manual = "manual"


class CommitPolicy(BaseModel):
    """Commit authority for a child plan (v1.9.0)."""

    mode: CommitPolicyMode | None = Field(
        None,
        description=(
            "'child_commit' = child commits within allowed_paths; "
            "'parent_commit' = parent plan lands the commit on the child's "
            "evidence; 'manual' = operator commits outside the supervisor."
        ),
    )
    requires: list[str] | None = Field(
        None,
        description=(
            "Compliance checks evaluated at close-out. Plain strings so the "
            "runtime can extend the vocabulary without a schema bump."
        ),
    )


class Plan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(
        pattern=r"^\d{4}-\d{2}-\d{2}-\d{3}-(feat|fix|refactor|migration|infra)-[a-z0-9-]+$"
    ) = Field(..., description="YYYY-MM-DD-NNN-<type>-<kebab-name>")
    title: constr(min_length=1, max_length=120)
    type: Type
    tier: Tier
    status: Status
    date: date_aliased
    description: constr(min_length=10)
    motivation: str | None = None
    agents_required: list[AgentsRequiredEnum] | None = None
    human_gates: list[HumanGate] | None = None
    quota_caps: QuotaCaps | None = Field(
        None,
        description="Per-model % weekly quota cap for this plan. OSS is unmetered (Ollama local).",
    )
    loop_caps: LoopCaps | None = None
    privacy_tier: PrivacyTier | None = None
    goal_type: GoalType | None = Field(
        None,
        description="Goal-completion governance category. When set to one of {parity, new_feature, migration, incident}, the plan must declare links.objective_contract pointing at an ObjectiveContract file. mechanical/infra/refactor plans don't require a contract; backward-compatible default is null/absent.",
    )
    surfaces: list[Surface] | None = Field(
        None,
        description="v1.7.0 — added external-api-wrap surface for plans whose goal is wrapping an existing OpenAPI-shaped service; consume via the printing-press-adapter skill (DontPanic claude/skills/).",
    )
    protected_paths: list[str] | None = Field(
        None, description="Path patterns that require human approval to modify"
    )
    open_decisions: list[OpenDecision] | None = None
    dependencies: list[str] | None = None
    links: Links | None = None
    storage: Storage | None = Field(
        None, description="External storage backend for evidence > 100KB"
    )
    orchestration: Orchestration | None = Field(
        None,
        description=(
            "v1.9.0 — child-plan nested-orchestration metadata. Absent on top-"
            "level plans; populated on child plans spawned by a parent."
        ),
    )
    child_charter: ChildCharter | None = Field(
        None,
        description=(
            "v1.9.0 — child-plan charter declaring bounded work, parent "
            "objective, allowed paths, and return condition. Only valid when "
            "orchestration.parent_plan_id is set."
        ),
    )
    commit_policy: CommitPolicy | None = Field(
        None,
        description=(
            "v1.9.0 — commit authority for a child plan. Mode is "
            "'child_commit', 'parent_commit', or 'manual' (see "
            "CommitPolicy.mode); absent commit_policy = supervisor falls "
            "through to default behavior (operator-explicit commit)."
        ),
    )
