# generated by datamodel-codegen:
#   filename:  plan.schema.json
#   timestamp: 2026-05-08T18:45:51+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Type(Enum):
    feat = "feat"
    fix = "fix"
    refactor = "refactor"
    migration = "migration"
    infra = "infra"


class Tier(Enum):
    trivial = "trivial"
    local = "local"
    cross_cutting = "cross-cutting"
    architectural = "architectural"
    p0 = "p0"


class Status(Enum):
    draft = "draft"
    active = "active"
    ready_for_audit = "ready_for_audit"
    in_audit = "in_audit"
    completed = "completed"
    abandoned = "abandoned"
    blocked = "blocked"


class AgentsRequiredEnum(Enum):
    claude = "claude"
    codex = "codex"
    gemini = "gemini"
    grok = "grok"
    oss_qwen = "oss-qwen"
    oss_gemma4 = "oss-gemma4"
    oss_nemotron = "oss-nemotron"
    oss_llama_guard = "oss-llama-guard"
    oss_nomic_embed = "oss-nomic-embed"


class HumanGate(Enum):
    pre_impl = "pre_impl"
    pre_merge = "pre_merge"
    on_escalation = "on_escalation"
    tier_promotion = "tier_promotion"
    cost_trigger = "cost_trigger"


class QuotaCaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    claude: confloat(ge=0.0, le=100.0) | None = None
    codex: confloat(ge=0.0, le=100.0) | None = None
    gemini: confloat(ge=0.0, le=100.0) | None = None
    grok_calls: conint(ge=0) | None = None


class LoopCaps(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_iterations: conint(ge=0) | None = None
    no_progress_threshold: conint(ge=1) | None = None
    wall_clock_hours: confloat(ge=0.0) | None = None
    hard_stop: bool | None = Field(
        None,
        description="true = terminate at cap; false (default) = pause for human approval via INBOX.md, reset counters on approval.",
    )


class PrivacyTier(Enum):
    public = "public"
    internal = "internal"
    secret = "secret"


class GoalType(Enum):
    mechanical = "mechanical"
    infra = "infra"
    refactor = "refactor"
    parity = "parity"
    new_feature = "new_feature"
    migration = "migration"
    incident = "incident"


class Surface(Enum):
    web = "web"
    ios = "ios"
    android = "android"
    backend = "backend"
    infra = "infra"
    security = "security"
    data = "data"
    ux = "ux"
    ml = "ml"
    docs = "docs"


class Status1(Enum):
    open = "open"
    resolved = "resolved"
    deferred = "deferred"


class OpenDecision(BaseModel):
    id: str
    question: str
    status: Status1
    resolution: str | None = None


class Links(BaseModel):
    features: str | None = None
    decisions: str | None = None
    audits_dir: str | None = None
    evidence_dir: str | None = None
    objective_contract: str | None = Field(
        None,
        description="Path reference (relative to plan dir) to an ObjectiveContract JSON file. Required when goal_type ∈ {parity, new_feature, migration, incident}; the plan-level validator enforces presence + file-exists + ObjectiveContract validation.",
    )


class Backend(Enum):
    firebase_storage = "firebase-storage"
    r2 = "r2"
    local = "local"


class Storage(BaseModel):
    backend: Backend | None = None
    bucket: str | None = None
    prefix: str | None = None


class Plan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: constr(
        pattern=r"^\d{4}-\d{2}-\d{2}-\d{3}-(feat|fix|refactor|migration|infra)-[a-z0-9-]+$"
    ) = Field(..., description="YYYY-MM-DD-NNN-<type>-<kebab-name>")
    title: constr(min_length=1, max_length=120)
    type: Type
    tier: Tier
    status: Status
    date: date_aliased
    description: constr(min_length=10)
    motivation: str | None = None
    agents_required: list[AgentsRequiredEnum] | None = None
    human_gates: list[HumanGate] | None = None
    quota_caps: QuotaCaps | None = Field(
        None,
        description="Per-model % weekly quota cap for this plan. OSS is unmetered (Ollama local).",
    )
    loop_caps: LoopCaps | None = None
    privacy_tier: PrivacyTier | None = None
    goal_type: GoalType | None = Field(
        None,
        description="Goal-completion governance category. When set to one of {parity, new_feature, migration, incident}, the plan must declare links.objective_contract pointing at an ObjectiveContract file. mechanical/infra/refactor plans don't require a contract; backward-compatible default is null/absent.",
    )
    surfaces: list[Surface] | None = Field(
        None,
        description="v1.5.0 — surface taxonomy this plan touches. Optional; backward-compatible default is absent. Consumed by skill-applicability matchers (DontPanic plan 2026-05-08-002) to surface which skills are advisory for the plan. Adding a new surface requires a v1.6.0 schema bump with explicit operator approval.",
    )
    protected_paths: list[str] | None = Field(
        None, description="Path patterns that require human approval to modify"
    )
    open_decisions: list[OpenDecision] | None = None
    dependencies: list[str] | None = None
    links: Links | None = None
    storage: Storage | None = Field(
        None, description="External storage backend for evidence > 100KB"
    )
