# generated by datamodel-codegen:
#   filename:  plan.schema.json
#   timestamp: 2026-05-06T00:26:14+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    feat = 'feat'
    fix = 'fix'
    refactor = 'refactor'
    migration = 'migration'
    infra = 'infra'


class Tier(Enum):
    trivial = 'trivial'
    local = 'local'
    cross_cutting = 'cross-cutting'
    architectural = 'architectural'
    p0 = 'p0'


class Status(Enum):
    draft = 'draft'
    active = 'active'
    ready_for_audit = 'ready_for_audit'
    in_audit = 'in_audit'
    completed = 'completed'
    abandoned = 'abandoned'
    blocked = 'blocked'


class AgentsRequiredEnum(Enum):
    claude = 'claude'
    codex = 'codex'
    gemini = 'gemini'
    grok = 'grok'
    oss_qwen = 'oss-qwen'
    oss_gemma4 = 'oss-gemma4'
    oss_nemotron = 'oss-nemotron'
    oss_llama_guard = 'oss-llama-guard'
    oss_nomic_embed = 'oss-nomic-embed'


class HumanGate(Enum):
    pre_impl = 'pre_impl'
    pre_merge = 'pre_merge'
    on_escalation = 'on_escalation'
    tier_promotion = 'tier_promotion'
    cost_trigger = 'cost_trigger'


class QuotaCaps(BaseModel):
    """
    Per-model % weekly quota cap for this plan. OSS is unmetered (Ollama local).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    claude: float | None = Field(None, ge=0.0, le=100.0)
    codex: float | None = Field(None, ge=0.0, le=100.0)
    gemini: float | None = Field(None, ge=0.0, le=100.0)
    grok_calls: int | None = Field(None, ge=0)


class LoopCaps(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_iterations: int | None = Field(None, ge=0)
    no_progress_threshold: int | None = Field(None, ge=1)
    wall_clock_hours: float | None = Field(None, ge=0.0)
    hard_stop: bool | None = None
    """
    true = terminate at cap; false (default) = pause for human approval via INBOX.md, reset counters on approval.
    """


class PrivacyTier(Enum):
    public = 'public'
    internal = 'internal'
    secret = 'secret'


class GoalType(Enum):
    """
    Goal-completion governance category. When set to one of {parity, new_feature, migration, incident}, the plan must declare links.objective_contract pointing at an ObjectiveContract file. mechanical/infra/refactor plans don't require a contract; backward-compatible default is null/absent.
    """

    mechanical = 'mechanical'
    infra = 'infra'
    refactor = 'refactor'
    parity = 'parity'
    new_feature = 'new_feature'
    migration = 'migration'
    incident = 'incident'


class Status1(Enum):
    open = 'open'
    resolved = 'resolved'
    deferred = 'deferred'


class OpenDecision(BaseModel):
    id: str
    question: str
    status: Status1
    resolution: str | None = None


class Links(BaseModel):
    features: str | None = None
    decisions: str | None = None
    audits_dir: str | None = None
    evidence_dir: str | None = None
    objective_contract: str | None = None
    """
    Path reference (relative to plan dir) to an ObjectiveContract JSON file. Required when goal_type ∈ {parity, new_feature, migration, incident}; the plan-level validator enforces presence + file-exists + ObjectiveContract validation.
    """


class Backend(Enum):
    firebase_storage = 'firebase-storage'
    r2 = 'r2'
    local = 'local'


class Storage(BaseModel):
    """
    External storage backend for evidence > 100KB
    """

    backend: Backend | None = None
    bucket: str | None = None
    prefix: str | None = None


class Plan(BaseModel):
    """
    Orchestration plan metadata. Narrative lives in plan.md frontmatter; this schema validates that frontmatter.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}-\\d{3}-(feat|fix|refactor|migration|infra)-[a-z0-9-]+$',
    )
    """
    YYYY-MM-DD-NNN-<type>-<kebab-name>
    """
    title: str = Field(..., max_length=120, min_length=1)
    type: Type
    tier: Tier
    status: Status
    date: date_aliased
    description: str = Field(..., min_length=10)
    motivation: str | None = None
    agents_required: list[AgentsRequiredEnum] | None = None
    human_gates: list[HumanGate] | None = None
    quota_caps: QuotaCaps | None = None
    """
    Per-model % weekly quota cap for this plan. OSS is unmetered (Ollama local).
    """
    loop_caps: LoopCaps | None = None
    privacy_tier: PrivacyTier | None = None
    goal_type: GoalType | None = None
    """
    Goal-completion governance category. When set to one of {parity, new_feature, migration, incident}, the plan must declare links.objective_contract pointing at an ObjectiveContract file. mechanical/infra/refactor plans don't require a contract; backward-compatible default is null/absent.
    """
    protected_paths: list[str] | None = None
    """
    Path patterns that require human approval to modify
    """
    open_decisions: list[OpenDecision] | None = None
    dependencies: list[str] | None = None
    links: Links | None = None
    storage: Storage | None = None
    """
    External storage backend for evidence > 100KB
    """
