# generated by datamodel-codegen:
#   filename:  signoff.schema.json
#   timestamp: 2026-04-25T18:36:50+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, conint


class Tier(Enum):
    trivial = 'trivial'
    local = 'local'
    cross_cutting = 'cross-cutting'
    architectural = 'architectural'
    p0 = 'p0'


class VoteSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    signed_off_count: conint(ge=0)
    needs_changes_count: conint(ge=0)
    blocked_count: conint(ge=0)
    inconclusive_count: conint(ge=0) | None = None


class Resolution(Enum):
    accept_finding = 'accept_finding'
    reject_finding = 'reject_finding'
    escalate_to_human = 'escalate_to_human'


class Disagreement(BaseModel):
    finding: str
    agents_pro: list[str]
    agents_con: list[str]
    rationale: str
    resolution: Resolution | None = None


class Reconciliation(BaseModel):
    agreements: list[dict[str, Any]] | None = Field(
        None, description='Findings from 2+ agents — high confidence'
    )
    disagreements: list[Disagreement] | None = Field(
        None, description='Conflicting findings + supervisor rationale'
    )
    security_veto: bool | None = Field(
        None,
        description='Codex flagged critical/high security. If true, signoff must be false regardless of vote.',
    )


class NextAction(Enum):
    merge = 'merge'
    remediate = 'remediate'
    escalate = 'escalate'
    defer = 'defer'
    blocked_awaiting_human = 'blocked_awaiting_human'


class QuotaConsumedTotal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claude_percent: float | None = None
    codex_percent: float | None = None
    gemini_percent: float | None = None
    grok_calls: int | None = None


class Escalation(BaseModel):
    reason: str | None = None
    inbox_entry_id: str | None = None
    human_response: str | None = None
    resolved_at: AwareDatetime | None = None


class Signoff(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    task_id: str
    signoff_id: str
    iteration: conint(ge=0)
    tier: Tier
    agents_in_panel: list[str] = Field(..., min_length=1)
    audits: list[str] = Field(..., min_length=1)
    vote_summary: VoteSummary | None = None
    reconciliation: Reconciliation | None = None
    signoff: bool
    signoff_reason: str | None = None
    next_action: NextAction
    quota_consumed_total: QuotaConsumedTotal | None = None
    escalation: Escalation | None = None
    decided_at: AwareDatetime
