# generated by datamodel-codegen:
#   filename:  state-snapshot.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class RedactLevel(Enum):
    """
    public = Observer role / unauth dashboards / CI status checks (no quota agent breakdown, no supervisor PIDs/hosts, no operator email, no file paths beyond plan_id). operator = default for authenticated operator-side adapters (full state minus secrets per scripts/sanitization_check.py SECRET_REGEXES). full = local-CLI-only escape hatch (includes all fields). MCP `state_snapshot` caps redact_level at `operator` regardless of caller request.
    """

    public = "public"
    operator = "operator"
    full = "full"


class Status(Enum):
    draft = "draft"
    active = "active"
    ready_for_audit = "ready_for_audit"
    in_audit = "in_audit"
    completed = "completed"
    abandoned = "abandoned"
    blocked = "blocked"


class Type(Enum):
    feat = "feat"
    fix = "fix"
    infra = "infra"
    refactor = "refactor"
    chore = "chore"
    docs = "docs"
    test = "test"


class Tier(Enum):
    trivial = "trivial"
    local = "local"
    cross_cutting = "cross-cutting"
    architectural = "architectural"
    p0 = "p0"


class GoalType(Enum):
    mechanical = "mechanical"
    infra = "infra"
    refactor = "refactor"
    parity = "parity"
    new_feature = "new_feature"
    migration = "migration"
    incident = "incident"


class FeaturesSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: conint(ge=0)
    passing: conint(ge=0)


class PlanSummary(BaseModel):
    """
    One entry per plan dir under docs/plans/. Status reflects the plan.md frontmatter; features_summary aggregates features.json passes counts.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: constr(
        pattern=r"^\d{4}-\d{2}-\d{2}-\d{3}-(feat|fix|infra|refactor|chore|docs|test)-[a-z0-9-]+$"
    )
    """
    Stable ID. Format: YYYY-MM-DD-NNN-type-slug. Never a SHA or internal identifier.
    """
    status: Status
    title: str
    type: Type | None = None
    tier: Tier | None = None
    goal_type: GoalType | None = None
    surfaces: list[str] | None = None
    """
    Per agent-conventions v1.5 — surfaces[] taxonomy (web, ios, android, backend, infra, ux, etc.)
    """
    features_summary: FeaturesSummary | None = None
    target_env: str | None = None
    """
    From plan Target section, e.g. dev / production / local
    """
    target_project: str | None = None
    """
    Plan-declared project_id or null for host-local plans
    """
    agents_required: list[str] | None = None
    date: str | None = None
    """
    Plan creation date (YYYY-MM-DD)
    """


class Kind(Enum):
    pre_impl = "pre_impl"
    pre_merge = "pre_merge"
    breaker = "breaker"
    defer = "defer"
    custom = "custom"


class GateEntry(BaseModel):
    """
    One entry per unmet (paused) gate across all plans. Cleared gates are not emitted in v0; downstream consumers infer clearance from absence.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: str
    gate_name: str
    """
    Stable name. Examples: `pre_impl`, `pre_merge`, `breaker:no_progress`, `breaker:budget_ceiling`, `defer:quota_threshold`, plan-declared custom gates.
    """
    kind: Kind
    stage: str | None = None
    """
    Lifecycle stage if kind is pre_impl or pre_merge; null otherwise.
    """
    reason: str | None = None
    """
    Human-readable reason the gate is paused. Redacted at `public` level.
    """
    paused_at: AwareDatetime
    approval_required: bool | None = None
    feature_id: constr(pattern=r"^F\d{3}$|^null$") | None = None


class InboxEvent(BaseModel):
    """
    One entry per recent INBOX.md event across all plans. Newest-first; limit configurable per gather.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: str
    event: str
    """
    Event kind. Examples: volley_start, gate_paused, breaker_tripped, signoff, calibration_required, no_progress_classification, environmental_blocker_short_circuit, verdict_mismatch, pre_impl_status_synced.
    """
    event_id: str
    """
    Stable composite: `<plan_id>:<event>:<captured_at>:<feature_id-or-empty>`. Adapter-stable across DontPanic refactors.
    """
    captured_at: AwareDatetime
    feature_id: constr(pattern=r"^F\d{3}$|^null$") | None = None
    body: str | None = None
    """
    Markdown event body. Truncated / redacted per redact_level. Reading the full body requires read_evidence on the underlying INBOX.md path (operator/full only).
    """
    headers: dict[str, str] | None = None
    """
    Key-value pairs from the INBOX header block (e.g. severity, gate_name, breaker_kind). Stable across DontPanic refactors of the INBOX writer.
    """


class SupervisorEntry(BaseModel):
    """
    One entry per active supervisor (from ~/.dontpanic/active_supervisors.jsonl).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    supervisor_id: str
    """
    Stable composite `<pid>:<started_at>`. Stays stable for the supervisor's lifetime.
    """
    plan_id: str
    feature_id: constr(pattern=r"^F\d{3}$|^null$") | None = None
    implementer_agent: str | None = None
    auditor_agent: str | None = None
    started_at: AwareDatetime
    host: str | None = None
    """
    Operator hostname. Redacted (set to null) at `public` redact_level.
    """
    pid: conint(ge=0) | None = None
    """
    Process ID. Only present at `full` redact_level; null at operator/public.
    """


class Vendor(Enum):
    """
    Vendor name. `public` redact_level may aggregate to a single 'total' entry instead of per-vendor breakdown.
    """

    claude = "claude"
    codex = "codex"
    gemini = "gemini"
    grok = "grok"


class Window(Enum):
    daily = "daily"
    weekly = "weekly"
    monthly = "monthly"


class Status1(Enum):
    ok = "ok"
    warn = "warn"
    exceeded = "exceeded"
    calibration_required = "calibration_required"
    config_required = "config_required"
    unit_mismatch = "unit_mismatch"


class QuotaEntry(BaseModel):
    """
    One entry per (vendor, window) pair from ~/.dontpanic/quota_state.json. Adapters render budget gauges and cap thresholds.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    vendor: Vendor
    """
    Vendor name. `public` redact_level may aggregate to a single 'total' entry instead of per-vendor breakdown.
    """
    window: Window
    percent_of_cap: confloat(ge=0.0) | None = None
    """
    Observed percent of the per-window cap. Null when no signal yet (uncalibrated).
    """
    percent_threshold: confloat(ge=0.0, le=100.0) | None = None
    """
    Soft-warn threshold (default 90).
    """
    status: Status1
    captured_at: AwareDatetime | None = None


class DecisionEntry(BaseModel):
    """
    One entry per decision (D-entry) across plans. Recent-first; limit configurable per gather. Body is redacted at `public` to title only.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: str
    decision_id: constr(pattern=r"^D\d{3}$")
    """
    D001, D002, ... — stable per plan.
    """
    ts: AwareDatetime
    by: str | None = None
    """
    Decision author (operator / reviewer / agent name). May be redacted at `public`.
    """
    title: str
    body: str | None = None
    """
    Decision body. Null at `public` redact_level (only title surfaces); full at operator/full levels.
    """


class Type1(Enum):
    screenshot = "screenshot"
    log = "log"
    test_output = "test_output"
    diff = "diff"
    audit_json = "audit_json"
    commit = "commit"
    url = "url"
    file = "file"


class EvidencePointer(BaseModel):
    """
    Pointers ONLY — never evidence file contents. Adapters use the URI to call MCP `read_evidence` if they need contents (which gates on operator role).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    plan_id: str
    feature_id: constr(pattern=r"^F\d{3}$")
    type: Type1
    uri: str
    """
    Relative path under the plan dir, git SHA, or operator-readable URL. Never a Firebase Storage signed URL with secrets.
    """
    captured_at: AwareDatetime | None = None
    captured_by: str | None = None
    note: str | None = None


class Streams(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    plans: list[PlanSummary]
    gates: list[GateEntry]
    inbox: list[InboxEvent]
    supervisors: list[SupervisorEntry]
    quota: list[QuotaEntry]
    decisions: list[DecisionEntry]
    evidence_refs: list[EvidencePointer]


class StateSnapshot(BaseModel):
    """
    Read-only state projection of a DontPanic operator's local plan/gate/inbox/supervisor/quota/decisions state. Emitted by `dontpanic state snapshot --json` and the MCP `state_snapshot` tool. Stable contract consumed by adapters (dashboards, brokers, CI runners, hosted-agent runtimes). Stable IDs across DontPanic refactors; redaction-aware; tz-aware UTC timestamps. Mutations are NEVER expressed via this schema — adapters call MCP tools (`approve_gate`, `dispatch`, `resume`, `read_evidence`) for state changes.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0"]
    """
    Locked at 1.0 for the v0 contract. Any breaking change to a stream shape requires a major schema bump and a deprecation window.
    """
    captured_at: AwareDatetime
    """
    RFC 3339 UTC timestamp at which the projection was gathered. Ends with `Z` for UTC.
    """
    dontpanic_version: str | None = None
    """
    Version of the DontPanic CLI that produced the snapshot. Adapters may use this for compatibility checks.
    """
    redact_level: RedactLevel
    """
    public = Observer role / unauth dashboards / CI status checks (no quota agent breakdown, no supervisor PIDs/hosts, no operator email, no file paths beyond plan_id). operator = default for authenticated operator-side adapters (full state minus secrets per scripts/sanitization_check.py SECRET_REGEXES). full = local-CLI-only escape hatch (includes all fields). MCP `state_snapshot` caps redact_level at `operator` regardless of caller request.
    """
    streams: Streams
